name: Deploy Automatico Saira

on:
  push:
    branches:
      - main      # Producao
      - develop   # Teste
    paths-ignore:
      - "services/ingester/**"

jobs:
  # --- AMBIENTE DE TESTE ---
  deploy-test:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Teste
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "--- INICIANDO DEPLOY DE TESTE (SAIRA) ---"

            cd /home/ubuntu/saira
            git fetch origin develop
            git reset --hard origin/develop

            cd services

            echo "Reiniciando Ambiente de Teste..."
            docker compose -p saira-test -f docker-compose.test.yml down
            docker compose -p saira-test -f docker-compose.test.yml up -d --build --force-recreate

            echo "Teste rodando (Projeto: saira-test)"

  # --- AMBIENTE DE PRODUCAO ---
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Producao
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "--- INICIANDO DEPLOY DE PRODUCAO (SAIRA) ---"

            cd /home/ubuntu/saira
            git fetch origin main
            git reset --hard origin/main

            cd services

            echo "Atualizando Producao..."
            docker compose -p saira-prod -f docker-compose.prod.yml build
            docker compose -p saira-prod -f docker-compose.prod.yml up -d

            echo "Producao rodando (Projeto: saira-prod)"
